name: Daily Learning Log

on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8:00 AM UTC every day
  workflow_dispatch:  # Optional: allows manual run

jobs:
  update-learning-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update learning log
        run: |
          total_lines=$(wc -l < topics.txt)
          day_of_year=$(date +%j | sed 's/^0*//')
          today_index=$(( (day_of_year % total_lines) + 1 ))
          topic=$(sed -n "${today_index}p" topics.txt)
          
          response=$(curl -s https://api.quotable.io/random)
          quote=$(echo "$response" | jq -r '.content')
          author=$(echo "$response" | jq -r '.author')

          echo "## 📅 $(date -u +'%Y-%m-%d')" >> learning_log.md
          echo "**🧠 Learning Topic:** $topic" >> learning_log.md
          echo "**💬 Quote of the Day:** \"$quote\" — $author" >> learning_log.md
          echo "" >> learning_log.md

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add learning_log.md
          git commit -m "📝 Daily log update: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
